### ISSUE TITLE
Create key contacts page

### ISSUE THREAD

**Issue by JasonTame** [jamestrevorlees/funda.fundawande.org#27]
![key_contacts_page](https://user-images.githubusercontent.com/15672948/53086451-cfe13280-350d-11e9-8176-54896114cc5c.png)

**Comment by cwbmuller** [comment]
➤ Jason Michael Tame commented:

Changes made to coach card james@pango.studio ( https://app.asana.com/0/1109906268313024/list ), PR is ready for review again 🙂
